/** Generated by validation/research-calendar/build-tiaohou-registry.py.
 * Reviewed transcription candidates are not executable rules or validated predictions.
 * Unreviewed entries deliberately have NO candidate stems. */
import type { TianGan, DiZhi } from './types';
export interface TiaoHouReview {
  ruleId: string; dayStem: TianGan; monthBranch: DiZhi; solarMonthOrdinal: number;
  reviewStatus: 'transcription-checked' | 'needs-source-review'; candidateStems: TianGan[];
  conditions: string[]; sourceDocument: string; sourceAnchor: string; excerpt: string;
  sourceSha256: string; editionStatus: 'online-transcription-unverified-against-printed-edition';
  automatedSelection: false;
}
export const TIAOHOU_REVIEWS: readonly TiaoHouReview[] = [
  {
    "ruleId": "qiongtong.甲寅",
    "dayStem": "甲",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸"
    ],
    "conditions": [
      "只记录初春余寒通论；须再核四柱寒暖及后续变例",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:38",
    "excerpt": "初春尚有余寒，得丙癸逢",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲卯",
    "dayStem": "甲",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚"
    ],
    "conditions": [
      "原段讨论阳刃驾杀且要求财资；不把庚列为所有甲卯命固定用神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:50",
    "excerpt": "庚金得所，名阳刃驾杀",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲辰",
    "dayStem": "甲",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "壬"
    ],
    "conditions": [
      "原文另有金局用丁、弃命从财等分支；不把壬列为固定忌神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:52",
    "excerpt": "先取庚金，次用壬水",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲巳",
    "dayStem": "甲",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丁"
    ],
    "conditions": [
      "庚太多及金火多有另论；先后是本段通论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:68",
    "excerpt": "退气，丙火司权，先癸后丁",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲午",
    "dayStem": "甲",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丁",
      "庚"
    ],
    "conditions": [
      "下文另论木盛先庚、庚盛先丁及乏癸；不能直接排除丁",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:76",
    "excerpt": "五月先癸后丁庚金次之",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲未",
    "dayStem": "甲",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "庚"
    ],
    "conditions": [
      "修正旧表癸丙；须同时审阅木盛、庚盛、从财等变例",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:76",
    "excerpt": "六月三伏生寒，丁火退气。先丁后庚，无癸亦可",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲申",
    "dayStem": "甲",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "庚"
    ],
    "conditions": [
      "丁须甲助；癸阻隔及戊制水是额外条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:110",
    "excerpt": "丁火为尊，庚金次之，庚金不可少",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲酉",
    "dayStem": "甲",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "丙",
      "庚"
    ],
    "conditions": [
      "下文木局比劫透则先庚后丁，次序不是无条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:112",
    "excerpt": "丁火为先，次用丙火，庚金再次",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲戌",
    "dayStem": "甲",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "壬",
      "癸"
    ],
    "conditions": [
      "另有木多专庚及从财例，须结合全局",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:126",
    "excerpt": "木星凋零，独爱丁火，壬癸滋扶",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲亥",
    "dayStem": "甲",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "丁",
      "丙"
    ],
    "conditions": [
      "同句忌壬泛身须戊制，不等于所有壬都忌",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:148",
    "excerpt": "庚丁为要，丙火次之",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲子",
    "dayStem": "甲",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "庚",
      "丙"
    ],
    "conditions": [
      "癸伤丁须戊己救应；丁缺时丙另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:156",
    "excerpt": "木性生寒，丁先庚后，丙火佐之",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.甲丑",
    "dayStem": "甲",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "丁"
    ],
    "conditions": [
      "前提为天寒木冻；完整格局另审",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jiamu.md",
    "sourceAnchor": "jiamu.md:164",
    "excerpt": "先用庚噼甲，方引丁火始得木火有通明之象，故丁次之",
    "sourceSha256": "84393a67854fc642ef5fdad1b810ccb843ec5fc794fe6afb9857c33132071651",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙寅",
    "dayStem": "乙",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸"
    ],
    "conditions": [
      "原文先解释余寒及癸水恐凝寒，非全局无条件结论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:34",
    "excerpt": "故以丙火为先，癸水次之",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙卯",
    "dayStem": "乙",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸"
    ],
    "conditions": [
      "需同时看不透庚、木局、水困丙等条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:40",
    "excerpt": "以丙为君，癸为臣",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙辰",
    "dayStem": "乙",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙"
    ],
    "conditions": [
      "只记录月段通论，未自动判别全局例外",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:50",
    "excerpt": "阳气愈炽，先癸后丙",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙巳",
    "dayStem": "乙",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙"
    ],
    "conditions": [
      "丙为酌用；原文另要求水源、金透及土困癸判别",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:68",
    "excerpt": "四月乙木专用癸水，丙火酌用",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙午",
    "dayStem": "乙",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙"
    ],
    "conditions": [
      "半月与金水多寡条件未自动求解，禁止直接选定第一候选",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:74",
    "excerpt": "上半月属阳，仍用癸水。下半月属阴，三伏生寒，丙癸齐用",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙未",
    "dayStem": "乙",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸"
    ],
    "conditions": [
      "丙优先以柱多金水为前提；癸另列候选不自动排序",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:80",
    "excerpt": "木性且寒，柱多金水，丙火为尊",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙申",
    "dayStem": "乙",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "己",
      "丙"
    ],
    "conditions": [
      "原文具体庚多/丙透条件需全局审阅；不沿用旧表丙癸概括",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:102",
    "excerpt": "有己透、加丙，亦是上命。七月喜己土为用",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙酉",
    "dayStem": "乙",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙"
    ],
    "conditions": [
      "有白露/秋分前后分支，当前仅保留条件，不自动决断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:110",
    "excerpt": "在白露之后，桂蕊未开，耑用癸水以滋桂萼。若秋分后，桂花已开，却喜向阳，又宜用丙",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙戌",
    "dayStem": "乙",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "辛"
    ],
    "conditions": [
      "辛为水源条件，甲申时藤萝系甲另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:124",
    "excerpt": "若见癸水，又遇辛金发水之源",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙亥",
    "dayStem": "乙",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "戊"
    ],
    "conditions": [
      "壬司令的通论，仍需全局条件核验",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:132",
    "excerpt": "取丙为用，戊土次之",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙子",
    "dayStem": "乙",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙"
    ],
    "conditions": [
      "同段讨论寒冻，不把古籍功名断语输出为现实结论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "yimu.md:136",
    "excerpt": "不宜用癸以冻花木，故耑用丙火",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.乙丑",
    "dayStem": "乙",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "needs-source-review",
    "candidateStems": [],
    "conditions": [
      "当前乙木转录缺少十二月独立条文；不得用十一月或其他版本推测填补。须补有版本依据的原文后再核候选。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/yimu.md",
    "sourceAnchor": "三冬乙木（本转录见十月与十一月，未见十二月独立段）",
    "excerpt": "",
    "sourceSha256": "19d4349e4c0eab50880d23a6b1c88e54f498eb6e83c8e4ce5901790d7fc2b0da",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙寅",
    "dayStem": "丙",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "庚"
    ],
    "conditions": [
      "通论候选；透藏与其他条件未自动判定",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:40",
    "excerpt": "取壬为尊，庚金佐之",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙卯",
    "dayStem": "丙",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬"
    ],
    "conditions": [
      "后文有丁壬化合、壬根、庚辛己透等条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:82",
    "excerpt": "阳气舒升，耑用壬水",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙辰",
    "dayStem": "丙",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲"
    ],
    "conditions": [
      "甲辅助以成土局为条件；无甲用庚另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:104",
    "excerpt": "气渐炎升，用壬水。或成土局，取甲为辅，壬不可离",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙巳",
    "dayStem": "丙",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "庚"
    ],
    "conditions": [
      "本段先专壬，庚发源；戊土及透藏条件须另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:118",
    "excerpt": "得庚发水源，方为有根之水",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙午",
    "dayStem": "丙",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "庚"
    ],
    "conditions": [
      "引用仅指候选，不采功名结论；有戊己、丁壬化合另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:142",
    "excerpt": "得壬高透，方为上命。或一壬无庚",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙未",
    "dayStem": "丙",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "庚"
    ],
    "conditions": [
      "通论候选，完整分支未自动解算",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:164",
    "excerpt": "退气，三伏生寒，壬水为用，取庚辅佐",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙申",
    "dayStem": "丙",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬"
    ],
    "conditions": [
      "此段为太阳转西通论，未评全局",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:188",
    "excerpt": "故仍用壬水，辅映光辉",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙酉",
    "dayStem": "丙",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬"
    ],
    "conditions": [
      "此段为八月通论，未评全局",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:202",
    "excerpt": "仍用壬水辅映",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙戌",
    "dayStem": "丙",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "壬",
      "癸"
    ],
    "conditions": [
      "癸是无壬的替代候选；不采现实富贵断言",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:224",
    "excerpt": "必须先用甲木，次取壬水。甲壬两透，富贵非凡。若无壬水，得癸透干，亦可",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙亥",
    "dayStem": "丙",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "戊",
      "庚"
    ],
    "conditions": [
      "同段另论辛透辰及化合逢时，不能把三候选统一作调候唯一定论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:246",
    "excerpt": "得见甲戊庚出干",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙子",
    "dayStem": "丙",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "戊"
    ],
    "conditions": [
      "同段以冬至为条件，不能把整个子月视同冬至后",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:264",
    "excerpt": "冬至一阳生，弱中复强，壬水为最，戊土佐之",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丙丑",
    "dayStem": "丙",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲"
    ],
    "conditions": [
      "甲以土多为条件，非所有命盘无条件并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/binghuo.md",
    "sourceAnchor": "binghuo.md:286",
    "excerpt": "喜壬为用。己土司令，土多又不可少甲",
    "sourceSha256": "54cb3fdb1e90ce2d4c06695a8bb3eba6d810051ea66bc683cb1a39d49857fc77",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁寅",
    "dayStem": "丁",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "甲"
    ],
    "conditions": [
      "原文为甲木当权的条件论；甲作为引火材料",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:34",
    "excerpt": "非庚不能噼甲，何以引丁，姑用庚金",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁卯",
    "dayStem": "丁",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "甲"
    ],
    "conditions": [
      "需要核乙旺、甲引及全局条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:56",
    "excerpt": "溼乙伤丁，先庚后甲，非庚不能去乙，非甲不能引丁",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁辰",
    "dayStem": "丁",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚"
    ],
    "conditions": [
      "以戊土司令泄丁为背景",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:76",
    "excerpt": "先用甲木引丁制土，次看庚金",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁巳",
    "dayStem": "丁",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚"
    ],
    "conditions": [
      "甲多又先庚；癸、壬与丙关系须另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:86",
    "excerpt": "虽取甲引丁，必用庚噼甲",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁午",
    "dayStem": "丁",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "庚",
      "甲"
    ],
    "conditions": [
      "火局用庚壬与无火局水透用甲庚为互斥条件分支，候选不合并自动取用",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:102",
    "excerpt": "得庚壬两透者",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁未",
    "dayStem": "丁",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "壬"
    ],
    "conditions": [
      "该段以阴柔退气、三伏生寒为背景",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:132",
    "excerpt": "专取甲木，壬水次之",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁申",
    "dayStem": "丁",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚",
      "丙"
    ],
    "conditions": [
      "丙暖晒等变例见同段；此处不自动取用",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:176",
    "excerpt": "退气柔弱，端用甲木，金虽乘旺司权，无伤丁之理，仍取庚劈甲",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁酉",
    "dayStem": "丁",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "丙",
      "庚",
      "乙"
    ],
    "conditions": [
      "乙是无甲时替代且不离丙晒；还有从财等分支，不自动并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:154",
    "excerpt": "八月甲丙庚皆用，七八月或无甲木，乙亦可用",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁戌",
    "dayStem": "丁",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚"
    ],
    "conditions": [
      "另见一派戊土伤官伤尽分支，全局未自动判定",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:154",
    "excerpt": "九月耑用甲庚",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁亥",
    "dayStem": "丁",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚",
      "癸",
      "戊"
    ],
    "conditions": [
      "三冬合论；癸戊为权宜，不得无条件作固定喜神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:226",
    "excerpt": "三冬丁火，甲木为尊，庚金佐之，癸戊权宜酌用可也",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁子",
    "dayStem": "丁",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚",
      "癸",
      "戊"
    ],
    "conditions": [
      "十一月水多无比印有从杀分支，不能仅依冬季通论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:226",
    "excerpt": "三冬丁火，甲木为尊，庚金佐之，癸戊权宜酌用可也",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.丁丑",
    "dayStem": "丁",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚",
      "癸",
      "戊"
    ],
    "conditions": [
      "采用季节共享段非单独十二月条；己合甲、丙夺丁等条件另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/dinghuo.md",
    "sourceAnchor": "dinghuo.md:226",
    "excerpt": "三冬丁火，甲木为尊，庚金佐之，癸戊权宜酌用可也",
    "sourceSha256": "3434882411c70aac50c08add54943fbdbd328ac1ab66233e3ce68c81b82c6286",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊寅",
    "dayStem": "戊",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲",
      "癸"
    ],
    "conditions": [
      "共同春段；遇火局等例外另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:42",
    "excerpt": "正二月先丙后甲，癸又次之",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊卯",
    "dayStem": "戊",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲",
      "癸"
    ],
    "conditions": [
      "共同春段；不能省略水火土全局条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:42",
    "excerpt": "正二月先丙后甲，癸又次之",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊辰",
    "dayStem": "戊",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "丙",
      "癸"
    ],
    "conditions": [
      "以戊土司权为背景，非通用固定喜忌",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:42",
    "excerpt": "三月先甲后丙，癸又次之",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊巳",
    "dayStem": "戊",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "丙",
      "癸"
    ],
    "conditions": [
      "原文强调外实内虚，与单纯夏土忌火概括不同",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:80",
    "excerpt": "故先用甲疏噼，次取丙癸为佐",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊午",
    "dayStem": "戊",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲",
      "丙"
    ],
    "conditions": [
      "丙为酌用，不可无条件加入喜神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:98",
    "excerpt": "先看壬水，次取甲木，丙火酌用，用癸力微",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊未",
    "dayStem": "戊",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙",
      "甲"
    ],
    "conditions": [
      "后文缺甲/丙等变例未自动解析",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:108",
    "excerpt": "先看癸水，次用丙火甲木",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊申",
    "dayStem": "戊",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸",
      "甲"
    ],
    "conditions": [
      "七月阳入寒出通论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:132",
    "excerpt": "先丙后癸，甲木次之",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊酉",
    "dayStem": "戊",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸"
    ],
    "conditions": [
      "不同于用木疏土的其他月份，须保留原文限定",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:148",
    "excerpt": "先丙后癸，不必木疏",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊戌",
    "dayStem": "戊",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "癸",
      "丙"
    ],
    "conditions": [
      "见金与化合条件会改变次序，当前候选不自动排序",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:156",
    "excerpt": "先看甲木，次取癸水，却忌化合。见金先用癸水，后取丙火",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊亥",
    "dayStem": "戊",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "丙"
    ],
    "conditions": [
      "寒土背景与全局条件待判断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:186",
    "excerpt": "先用甲木，次取丙火",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊子",
    "dayStem": "戊",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲"
    ],
    "conditions": [
      "原文十一二月合论，其他分支不自动推导",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:204",
    "excerpt": "严寒冰冻，丙火为专，甲木为佐",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.戊丑",
    "dayStem": "戊",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲"
    ],
    "conditions": [
      "原文十一二月合论，其他分支不自动推导",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/wutu.md",
    "sourceAnchor": "wutu.md:204",
    "excerpt": "严寒冰冻，丙火为专，甲木为佐",
    "sourceSha256": "d7cf630b217ed2286e313ee232a6f84def43dbcbbd5084fd337d83905b22aba9",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己寅",
    "dayStem": "己",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "戊"
    ],
    "conditions": [
      "戊只在壬多需堤时为条件候选，不无条件并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:42",
    "excerpt": "余寒未退，故丙为尊",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己卯",
    "dayStem": "己",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "癸"
    ],
    "conditions": [
      "明确有忌合条件；原文丙透另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:50",
    "excerpt": "先取甲木疏之，忌合。次取癸水润之",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己辰",
    "dayStem": "己",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "癸",
      "甲"
    ],
    "conditions": [
      "后文要求得地且论庚病，不将候选直接判定为已成立用神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:70",
    "excerpt": "先丙后癸，土暖而润，随用甲疏",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己巳",
    "dayStem": "己",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙",
      "辛"
    ],
    "conditions": [
      "三夏共论，辛生癸为条件且忌戊癸化合；未自动求解",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:92",
    "excerpt": "取癸为要，次用丙火",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己午",
    "dayStem": "己",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙",
      "辛"
    ],
    "conditions": [
      "三夏共享段，有丙无癸可壬、火烈制辛等分支；不可把候选无条件并用",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:92",
    "excerpt": "取癸为要，次用丙火",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己未",
    "dayStem": "己",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙",
      "辛"
    ],
    "conditions": [
      "三夏共享段，须结合水源、火烈与合化条件，不声称有独立六月定本条文",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:92",
    "excerpt": "取癸为要，次用丙火",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己申",
    "dayStem": "己",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙",
      "辛"
    ],
    "conditions": [
      "三秋共享段；有壬无丙及金局等不同条件未自动判断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:134",
    "excerpt": "三秋己土，先癸后丙，取辛辅癸",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己酉",
    "dayStem": "己",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "丙",
      "辛"
    ],
    "conditions": [
      "八月金局另论丙丁救，候选为共同通论，非唯一解",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:134",
    "excerpt": "三秋己土，先癸后丙，取辛辅癸",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己戌",
    "dayStem": "己",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "癸",
      "丙",
      "辛"
    ],
    "conditions": [
      "月别甲疏为重点，癸丙辛来自三秋共享段，均须全局条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:134",
    "excerpt": "九月土盛，宜甲木疏之，余皆酌用",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己亥",
    "dayStem": "己",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲",
      "戊"
    ],
    "conditions": [
      "戊仅初冬壬旺例外，甲为参酌，不自动并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:150",
    "excerpt": "取丙为尊，甲木参酌。戊土癸水不用。惟初冬壬旺，取戊制之",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己子",
    "dayStem": "己",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲",
      "丁"
    ],
    "conditions": [
      "三冬共享段；丁辅助不能等同丙解冻，全局从财等分支另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:150",
    "excerpt": "取丙为尊，甲木参酌",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.己丑",
    "dayStem": "己",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲",
      "丁"
    ],
    "conditions": [
      "三冬共享段；不把季节总论假写成独立十二月原句",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/jitu.md",
    "sourceAnchor": "jitu.md:150",
    "excerpt": "取丙为尊，甲木参酌",
    "sourceSha256": "260627d8cd3d7351ff45c7c189d7a7b89d38162aba6b98115531b1a747bb7916",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚寅",
    "dayStem": "庚",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲"
    ],
    "conditions": [
      "甲为防土厚埋金的条件候选",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:20",
    "excerpt": "先用丙暖庚性，又虑土厚埋金，须甲疏洩",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚卯",
    "dayStem": "庚",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "甲",
      "庚"
    ],
    "conditions": [
      "无丁用丙为后续分支；此处仅列原文组合",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:42",
    "excerpt": "专用丁火，借甲引丁，借庚噼甲",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚辰",
    "dayStem": "庚",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "丁"
    ],
    "conditions": [
      "保留不用庚劈甲这一明确限定",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:70",
    "excerpt": "故先甲后丁，不用庚噼甲",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚巳",
    "dayStem": "庚",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "戊",
      "丙"
    ],
    "conditions": [
      "先壬、戊与丙为不同角色，不简化为所有夏金同表",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:90",
    "excerpt": "但先壬水，方得中和，故曰群金生夏，喜用勾陈。次取戊土，丙火佐之",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚午",
    "dayStem": "庚",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "癸"
    ],
    "conditions": [
      "原文另有戊己透制水等条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:100",
    "excerpt": "专用壬水，癸又次之",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚未",
    "dayStem": "庚",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "甲"
    ],
    "conditions": [
      "忌癸伤丁等条件另审，不自动判断成格",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:106",
    "excerpt": "先用丁火，次取甲木",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚申",
    "dayStem": "庚",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "甲"
    ],
    "conditions": [
      "原文秋金通论，全局条件另审",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:128",
    "excerpt": "专用丁火煅炼，次取甲木引丁",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚酉",
    "dayStem": "庚",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "甲",
      "丙"
    ],
    "conditions": [
      "阳刃驾杀等条件需完整结构判断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:136",
    "excerpt": "用丁用甲，丙不可少",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚戌",
    "dayStem": "庚",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "壬"
    ],
    "conditions": [
      "以土厚埋金为背景，并有忌己浊壬条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:158",
    "excerpt": "宜先用甲疏，后用壬洗",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚亥",
    "dayStem": "庚",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "丙",
      "甲"
    ],
    "conditions": [
      "丙暖与丁炼角色不同；水局、己制等条件另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:180",
    "excerpt": "非丁莫造，非丙不暖。丁甲两透",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚子",
    "dayStem": "庚",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "甲",
      "丙"
    ],
    "conditions": [
      "多种透藏与缺位变例，当前不自动定用",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:194",
    "excerpt": "仍取丁甲，次取丙火照暖",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.庚丑",
    "dayStem": "庚",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "丁",
      "甲"
    ],
    "conditions": [
      "寒湿背景，非所有庚金通用同序",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/gengjin.md",
    "sourceAnchor": "gengjin.md:214",
    "excerpt": "先取丙火解冻，次取丁火炼金，甲亦不可少",
    "sourceSha256": "1a1f6218a2f4efb07adbc50aeb6040022101cef0f5e8111c0f03a4c3677732a6",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛寅",
    "dayStem": "辛",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "己",
      "壬"
    ],
    "conditions": [
      "同时有甲司权及庚制甲条件，未自动判断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:20",
    "excerpt": "取己土为生身之本，欲得辛金发现，全赖壬水之功",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛卯",
    "dayStem": "辛",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲"
    ],
    "conditions": [
      "甲针对土病的条件候选，不无条件并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:34",
    "excerpt": "壬水为尊，见戊己为病。得甲制伏",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛辰",
    "dayStem": "辛",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲"
    ],
    "conditions": [
      "需要全局透藏与土旺条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:64",
    "excerpt": "母旺子相，先壬后甲",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛巳",
    "dayStem": "辛",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬"
    ],
    "conditions": [
      "金局、木制戊及透藏条件另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:74",
    "excerpt": "忌丙火之燥烈，喜壬水之洗淘",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛午",
    "dayStem": "辛",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "己",
      "壬",
      "癸"
    ],
    "conditions": [
      "癸为无壬替代，火局又有不同条件；候选不是固定优先级",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:84",
    "excerpt": "须己壬兼用",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛未",
    "dayStem": "辛",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "庚",
      "甲"
    ],
    "conditions": [
      "甲仅在戊出等条件下使用，原文又明确无戊有己时不可甲",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:94",
    "excerpt": "先用壬水，取庚佐之",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛申",
    "dayStem": "辛",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲",
      "戊"
    ],
    "conditions": [
      "甲戊为依金水土结构酌用，不自动判成固定喜忌",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:112",
    "excerpt": "壬水为尊，甲戊酌用可也，癸水不可为用",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛酉",
    "dayStem": "辛",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲"
    ],
    "conditions": [
      "甲针对戊己土病；原文无戊不宜甲，不自动并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:118",
    "excerpt": "专用壬水淘洗火",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛戌",
    "dayStem": "辛",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "甲"
    ],
    "conditions": [
      "戊司令条件与透藏位置另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:146",
    "excerpt": "须甲疏土，壬洩旺金，先壬后甲",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛亥",
    "dayStem": "辛",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "丙"
    ],
    "conditions": [
      "小阳、寒气将降的月段通论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:174",
    "excerpt": "先用壬水，次取丙火",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛子",
    "dayStem": "辛",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "丙"
    ],
    "conditions": [
      "必须保留不见戊癸的条件，不无条件判吉",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:180",
    "excerpt": "壬丙两透，不见戊癸",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.辛丑",
    "dayStem": "辛",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "壬"
    ],
    "conditions": [
      "寒冻背景，不能把用途等同实证人格",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/xinjin.md",
    "sourceAnchor": "xinjin.md:188",
    "excerpt": "先丙后壬，无丙不能解冻，无壬不能洗淘",
    "sourceSha256": "2d946a233463c22d1ad07578f1f668c0c035dc26160c368aa4d97c1f4e19b65c",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬寅",
    "dayStem": "壬",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "丙",
      "戊"
    ],
    "conditions": [
      "丙戊见同段组合，非无条件次序",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:34",
    "excerpt": "宜用庚金之源",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬卯",
    "dayStem": "壬",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "戊",
      "辛",
      "庚"
    ],
    "conditions": [
      "不沿用泛化春水表；后文变例待结合全局",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:48",
    "excerpt": "二月壬水，先戊后辛，庚金次之",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬辰",
    "dayStem": "壬",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "庚"
    ],
    "conditions": [
      "以戊土司权为背景",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:58",
    "excerpt": "先用甲疏季土，次取庚金",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬巳",
    "dayStem": "壬",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "壬",
      "辛",
      "庚"
    ],
    "conditions": [
      "保留辛合丙的原文语境，具体能否化合另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:70",
    "excerpt": "专取壬水比肩为助，次取辛金发源，且暗合丙火，庚金为佐",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬午",
    "dayStem": "壬",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "癸",
      "庚",
      "辛"
    ],
    "conditions": [
      "辛癸可参用见同段，不据此自动三者皆取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:92",
    "excerpt": "取癸为用，取庚为佐",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬未",
    "dayStem": "壬",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "辛",
      "甲",
      "癸"
    ],
    "conditions": [
      "同段先述辛癸后甲，存在论述次序差异，保留候选而不强排",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:106",
    "excerpt": "六月壬水，先辛后甲，次取癸水",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬申",
    "dayStem": "壬",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "戊",
      "丁"
    ],
    "conditions": [
      "辰戌戊与申中戊的区别、戊癸合条件不可省略",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:112",
    "excerpt": "专用戊土，次取丁火佐戊制庚",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬酉",
    "dayStem": "壬",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲"
    ],
    "conditions": [
      "甲制戊且忌庚破的条件，不能直推所有命局固定忌土",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:132",
    "excerpt": "忌戊土为病，专用甲木",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬戌",
    "dayStem": "壬",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "甲",
      "丙"
    ],
    "conditions": [
      "前文一派壬与一派戊条件不同，保留候选不自动压成唯一解释",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:162",
    "excerpt": "九月壬水，专用甲木，次用丙火",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬亥",
    "dayStem": "壬",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "戊",
      "庚"
    ],
    "conditions": [
      "庚制甲不伤戊的条件见后文，不直接加入固定喜神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:174",
    "excerpt": "取戊为用",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬子",
    "dayStem": "壬",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "戊",
      "丙"
    ],
    "conditions": [
      "阳刃帮身背景，透藏另论",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:188",
    "excerpt": "先取戊土，次用丙火",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.壬丑",
    "dayStem": "壬",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "甲"
    ],
    "conditions": [
      "上半月仅专丙；上下半月条件当前未自动求解",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/renshui.md",
    "sourceAnchor": "renshui.md:206",
    "excerpt": "下半月己土主事，故衰。亦用丙火，甲木佐之",
    "sourceSha256": "30b7d8687d15a7266445fb53394d6bf3340519f4e732f41c9299b9a917fbfc79",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸寅",
    "dayStem": "癸",
    "monthBranch": "寅",
    "solarMonthOrdinal": 1,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "辛",
      "丙"
    ],
    "conditions": [
      "三阳背景和后文透藏条件未自动判断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:34",
    "excerpt": "先用辛金，生癸水之源，次用丙火照暖",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸卯",
    "dayStem": "癸",
    "monthBranch": "卯",
    "solarMonthOrdinal": 2,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "辛"
    ],
    "conditions": [
      "原文丁出等条件另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:44",
    "excerpt": "专以庚金为用，辛金次之",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸辰",
    "dayStem": "癸",
    "monthBranch": "辰",
    "solarMonthOrdinal": 3,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "辛",
      "甲"
    ],
    "conditions": [
      "清明/谷雨前后改变组合，当前不自动判定完整条件",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:60",
    "excerpt": "清明后、火气未炽，专用丙火，为阴阳合谐。谷雨后，虽用丙火，尚宜辛甲佐之",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸巳",
    "dayStem": "癸",
    "monthBranch": "巳",
    "solarMonthOrdinal": 4,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "辛",
      "庚"
    ],
    "conditions": [
      "庚是缺辛时替代，不是同时固定喜神",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:84",
    "excerpt": "喜辛金为用，无辛用庚",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸午",
    "dayStem": "癸",
    "monthBranch": "午",
    "solarMonthOrdinal": 5,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "辛",
      "壬"
    ],
    "conditions": [
      "金敌火需比劫等条件未自动求解",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:88",
    "excerpt": "五月癸水，庚辛壬参酌并用可也",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸未",
    "dayStem": "癸",
    "monthBranch": "未",
    "solarMonthOrdinal": 6,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "辛"
    ],
    "conditions": [
      "原文上下半月与比劫、丁透区别必须保留，不自动唯一取用",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:94",
    "excerpt": "所以专用庚辛",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸申",
    "dayStem": "癸",
    "monthBranch": "申",
    "solarMonthOrdinal": 7,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丁",
      "甲"
    ],
    "conditions": [
      "甲是丁有焰条件，金多及水制条件另判",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:106",
    "excerpt": "必取丁火为用。或丁透有甲",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸酉",
    "dayStem": "癸",
    "monthBranch": "酉",
    "solarMonthOrdinal": 8,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "辛",
      "丙"
    ],
    "conditions": [
      "原文要求丙辛隔位等条件，不能无条件说已成化",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:122",
    "excerpt": "故取辛金为用，丙火佐之",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸戌",
    "dayStem": "癸",
    "monthBranch": "戌",
    "solarMonthOrdinal": 9,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "辛",
      "癸",
      "甲"
    ],
    "conditions": [
      "须组合辛、比肩、甲及制戊条件，未自动判断",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:134",
    "excerpt": "专用辛金发水之源，要比肩滋甲制戊方妙",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸亥",
    "dayStem": "癸",
    "monthBranch": "亥",
    "solarMonthOrdinal": 10,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "庚",
      "辛"
    ],
    "conditions": [
      "原文不见丁伤等条件未自动求解",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:148",
    "excerpt": "宜用庚辛为妙",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸子",
    "dayStem": "癸",
    "monthBranch": "子",
    "solarMonthOrdinal": 11,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "辛"
    ],
    "conditions": [
      "后文壬癸与破丙的条件需保留",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:162",
    "excerpt": "专用丙火解冻，庶不致成冰，又要辛金滋扶",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  },
  {
    "ruleId": "qiongtong.癸丑",
    "dayStem": "癸",
    "monthBranch": "丑",
    "solarMonthOrdinal": 12,
    "reviewStatus": "transcription-checked",
    "candidateStems": [
      "丙",
      "壬"
    ],
    "conditions": [
      "壬仅为后文组合候选，是否见戊会改变解释，不自动并取",
      "候选仅表示此转录本中的传统论述；全局条件与印刷底本尚未完全核验，不自动选定用神。"
    ],
    "sourceDocument": "docs/mingli/source-texts/bazi/qiongtong-baojian/guishui.md",
    "sourceAnchor": "guishui.md:172",
    "excerpt": "宜丙火解冻",
    "sourceSha256": "28ac65719c2ee907eea8a2bf7198cfabfe409cb3f6b7eeb0fa0b4d5304f5f439",
    "editionStatus": "online-transcription-unverified-against-printed-edition",
    "automatedSelection": false
  }
];

export function getTiaoHouReview(dayStem: TianGan, monthBranch: DiZhi): TiaoHouReview {
  const row = TIAOHOU_REVIEWS.find(r => r.dayStem === dayStem && r.monthBranch === monthBranch);
  if (!row) throw new RangeError('调候条目不存在');
  return { ...row, candidateStems: [...row.candidateStems], conditions: [...row.conditions] };
}
