import { ZiweiEngine } from '../ZiweiEngine';

const engine = new ZiweiEngine();
// Hand-derived: 寅起正月顺数月，子时命身同宫；五虎遁/纳音局；
// 安紫微补数法（补至局数整除，寅起商数，补数奇退偶进）。
// These are literal expectations, not snapshots generated by iztro.
const cases = [
  { date: '2023-04-04', next: '2023-04-05', lunar: [2023,2,15], leap: true, ming: '卯', ganZhi: '乙卯', bureau: '水二局', ziwei: '申' },
  { date: '2023-04-05', next: '2023-04-06', lunar: [2023,2,16], leap: true, ming: '辰', ganZhi: '丙辰', bureau: '土五局', ziwei: '酉' },
  { date: '2023-04-06', next: '2023-04-07', lunar: [2023,2,17], leap: true, ming: '辰', ganZhi: '丙辰', bureau: '土五局', ziwei: '寅' },
  { date: '2024-04-08', next: '2024-04-09', lunar: [2024,3,1], leap: false, ming: '辰', ganZhi: '戊辰', bureau: '木三局', ziwei: '辰' },
  { date: '2024-02-09', next: '2024-02-10', lunar: [2024,1,1], leap: false, ming: '寅', ganZhi: '丙寅', bureau: '火六局', ziwei: '酉' },
];
function birth(date: string, hour: number) {
  const [year, month, day] = date.split('-').map(Number);
  return { year, month, day, hour, gender: '男' as const };
}

describe('selected zi-hour full calendar rollover', () => {
  for (const f of cases) it(`${f.date} 23:00 uses one consistent lunar date, month and year`, () => {
    const { pan, astrolabe } = engine.computeWithAstrolabe(birth(f.date, 23));
    expect(pan.mingGongPosition).toBe(f.ming);
    expect(pan.shenGongPosition).toBe(f.ming);
    expect(pan.palaces.find(p => p.name === '命宫')?.ganZhi).toBe(f.ganZhi);
    expect(pan.fiveElementsClass).toBe(f.bureau);
    expect(pan.palaces.find(p => p.mainStars.some(s => s.name === '紫微'))?.position).toBe(f.ziwei);
    expect(astrolabe.rawDates.lunarDate).toMatchObject({
      lunarYear: f.lunar[0], lunarMonth: f.lunar[1], lunarDay: f.lunar[2], isLeap: f.leap,
    });
    expect(pan.birthDateTime.toISOString()).toBe(`${f.date}T15:00:00.000Z`);
    expect(pan.method).toMatchObject({ calculationDate: f.next, civilTimeZone: 'UTC+08:00', dayBoundary: 'zi-hour' });
    // Integration property in addition to independent expected facts.
    expect(pan.palaces).toEqual(engine.compute(birth(f.next, 0)).palaces);
  });

  it('rolls the natal year transformations together, while 22:59 retains the old year', () => {
    const old = engine.compute({ ...birth('2024-02-09', 22), minute: 59 });
    const next = engine.compute(birth('2024-02-09', 23));
    const stars = (p: typeof next) => ['化禄','化权','化科','化忌'].map(label =>
      p.palaces.flatMap(x => [...x.mainStars, ...x.minorStars]).find(s => s.sihua?.some(h => h === label))?.name);
    expect(stars(old)).toEqual(['破军','巨门','太阴','贪狼']);
    expect(stars(next)).toEqual(['廉贞','破军','武曲','太阳']);
    expect(old.method).toMatchObject({ calculationDate: '2024-02-09' });
  });

  it('normalizes lunar leap input once without changing birth identity', () => {
    const lunar = engine.compute({ year:2023, month:2, day:16, hour:23, minute:59, gender:'男', isLunar:true, isLeapMonth:true });
    expect(lunar.mingGongPosition).toBe('辰');
    expect(lunar.palaces.find(p => p.mainStars.some(s => s.name === '紫微'))?.position).toBe('寅');
    expect(lunar.palaces).toEqual(engine.compute(birth('2023-04-07', 0)).palaces);
    expect(lunar.birthDateTime.toISOString()).toBe('2023-04-06T15:59:00.000Z');
    expect(lunar.method).toMatchObject({ calculationDate: '2023-04-07' });
  });

  it('accepts the last supported civil birth even when the calculation date is next year', () => {
    const { pan, astrolabe } = engine.computeWithAstrolabe(birth('2100-12-31', 23));
    expect(pan.birthDateTime.toISOString()).toBe('2100-12-31T15:00:00.000Z');
    expect(pan.method).toMatchObject({ calculationDate:'2101-01-01' });
    expect(astrolabe.rawDates.lunarDate).toMatchObject({ lunarYear:2100, lunarMonth:12, lunarDay:2 });
    expect(() => engine.compute(birth('2101-01-01', 0))).toThrow('invalid ziwei year');
  });
});
